name: make test
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '*.txt'
    - '*.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '*.txt'
    - '*.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
